### PR TITLE
Folia Support

### PR DESCRIPTION
**Pull request by ItsRainingHP**
Added Folia module which utilizes GlobalRegionScheduler.

### CODE REVIEW

**Comment by chickeneer** [comment]
I think I am probably on this repo and what-not. I'll take a look at it later today or tomorrow.

In general. I will say that this PR would indeed add some bare minimum folia compatibility. But it is incomplete in the grand picture of the goals of Folia. Specifically, that someone's goal shouldn't be to use the global scheduler sync for many things, but we need to design a new api which syncs to some region's scheduler. If that makes sense. Whereas 'traditional' mc just has sync or async - main thread or async. Folia would have all of its different "regions" that needs to be an option for taskchain to attach to.

**Comment by ItsRainingHP** [comment]
I agree. This was just bare minimum support to make it work. I intended to add region specific scheduling but wanted to put it out there for review.

**Comment by chickeneer** [comment]
Yeah, if you PR it, I can get it merged. I don't see myself committing to much more than that for folia :/

**Comment by ItsRainingHP** [comment]
I understand. Its not officially released yet, but I do want to add Folia support to my plugin eventually.

**Pull request closed without merging**
